#!/usr/bin/env ruby

require 'optparse'

module Conquer
  options = {}
  parser = OptionParser.new do |p|
    p.banner = 'Usage: conquer [options] bar.rb'
    p.on('-f', '--fifo=PATH', 'use/create rpc fifo in PATH') do |path|
      options[:fifo] = path
    end

    p.on('-h', '--help') do
      puts p
      exit
    end
  end

  parser.parse!
  abort(parser.to_s) if ARGV.empty?

  runtime_dir = ENV['XDG_RUNTIME_DIR'] || "/run/user/#{ENV['UID']}"
  FIFO = options[:fifo] || "#{runtime_dir}/conquer.fifo"
end

require 'conquer'

file=ARGV[0]
file.prepend("#{ENV['PWD']}/") unless file.start_with?('/')
require File.join(file)
