#!/usr/bin/env ruby

require 'optparse'

module Conquer
  options = {}
  parser = OptionParser.new do |p|
    p.banner = 'Usage: conquer [options] bar.rb'
    p.on('-s', '--socket=PATH', 'use rpc socket in PATH') do |path|
      options[:socket] = path
    end

    p.on('-h', '--help') do
      puts p
      exit
    end
  end

  parser.parse!
  abort(parser.to_s) if ARGV.empty?

  runtime_dir = ENV['XDG_RUNTIME_DIR'] || "/run/user/#{ENV['UID']}"
  RPC_SOCKET = options[:socket] || "#{runtime_dir}/conquer.socket"
end

begin
  require 'conquer'
  conquer_file = ARGV[0].to_s
  unless conquer_file.start_with?('/')
    conquer_file = File.join(ENV['PWD'], conquer_file)
  end
  require conquer_file
ensure
  File.delete(Conquer::RPC_SOCKET) if File.exist?(Conquer::RPC_SOCKET)
end
